# GET http://localhost:3000

POST http://localhost:8010/post
Content-Type: text/plain

Hello World
###

POST http://localhost:8010/post
Content-Type: text/plain

<br>Line break
###

POST http://localhost:8010/post
Content-Type: text/plain

\#
###

POST http://typewriter.meen.ch/post
Content-Type: text/plain

Hello World
###

POST http://typewriter.meen.ch/post
Content-Type: text/plain

<br>Line break
###

POST http://typewriter.meen.ch/post
Content-Type: text/plain

\#
###

POST https://lastip.services.campusderkuenste.ch/test123

###