# GET http://localhost:3000

POST http://localhost:8010/post
Content-Type: text/plain

H
###

POST http://localhost:8010/post
Content-Type: text/plain

e
###

POST http://localhost:8010/post
Content-Type: text/plain

l
###

POST http://localhost:8010/post
Content-Type: text/plain

l
###

POST http://localhost:8010/post
Content-Type: text/plain

o
###

POST http://localhost:8010/post
Content-Type: text/plain

 in Docker
###

POST https://typewriter.meen.ch/post
Content-Type: text/plain

Hello DATA
###

POST https://typewriter.meen.ch/post
Content-Type: text/plain

 in Production
###

GET https://typewriter.meen.ch/reset
Content-Type: text/plain

###